### ISSUE TITLE
Intercept outside crates' access to dependencies

### ISSUE THREAD

**Issue by lkatalin** [seedwing-io/seedwing-proxy#7]
The crates-io index specifies where to find relevant crates. After retrieving the index, cargo uses this index to find where to download the relevant crates, bypassing the proxy. We need a way to incorporate the proxy into this process, such that the policy will determine whether the crate can be used as a dependency.

**Comment by lkatalin** [comment]
In critical path of this issue:
- [ ] #13
- [ ] #14 
- [ ] #15

**Comment by knrc** [comment]
@lkatalin The code in https://github.com/seedwing-io/seedwing-proxy/pull/16 handles this for git index repositories, and the sparse protocol is handled in https://github.com/seedwing-io/seedwing-proxy/pull/24.  I think we can close this
